project:
  type: website
  output-dir: docs

website:
  title: "Apriandito"
  navbar:
    left:
      - href: index.qmd
        text: Tentang
      - href: blog.qmd
        text: Blog
    right: 
      - icon: twitter
        href: https://twitter.com/otidnairpa
      - icon: github
        href: https://github.com/apriandito

format:
  html:
    theme: Zephyr
    css: styles.css
    toc: true
    
execute:
  freeze: auto

editor: visual

