project:
  type: website
  output-dir: docs
website:
  title: "Apriandito"
  navbar:
    background: primary
    search: true
    pinned: true
    left:
      - href: blog.qmd
        text: Blog
    right: 
      - icon: github
        href: https://github.com/apriandito
  page-footer: 
    left: "Made with Code, ☕,  and ❤️" 
    right: "© Copyright Muhammad Apriandito | 2024"        
format:
  html:
    theme: zephyr
    css: www/styles.css
    toc: true
execute:
  freeze: auto
editor: visual
