project:
  type: website
  output-dir: docs

website:
  title: "Apriandito"
  navbar:
    left:
      - href: index.qmd
        text: Tentang
      - href: blog.qmd
        text: Blog
    right: 
      - icon: twitter
        href: https://twitter.com/otidnairpa
      - icon: github
        href: https://github.com/apriandito
        
  page-footer: 
    left: "Made with Love and Code" 
    right: "© Copyright Muhammad Apriandito | 2022"        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
execute:
  freeze: auto

editor: visual

