project:
  type: website
  output-dir: docs
website:
  title: "Apriandito"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: About
      - href: blog.qmd
        text: Blog
  page-footer: 
    left: "Made with Code and ❤️" 
    right: "© Copyright Muhammad Apriandito | 2024"        
format:
  html:
    theme: zephyr
    css: www/styles.css
    toc: true
execute:
  freeze: auto
editor: visual
