---
title: "Jangan update R dengan cara ini. Sebaiknya lakukan hal ini sebelum menyesal"
author: "Muhammad Apriandito"
date: "8/12/2022"
categories:
  - Opini
---

------------------------------------------------------------------------

Beberapa waktu lalu, R update ke versi 4.2.1 - *"Funny-Looking Kid"*. Lucu sekali namanya.

Nah entah mengapa, tidak ada angin, tidak ada hujan. Saya yang biasanya jarang update R, tiba-tiba tertarik megupdatenya. Pergilah saya ke CRAN kemudian mendownload R untuk windows, dan langsung saya install tanpa ba-bi-bu. Saya fikir toh update biasa ini. Seperti biasa next, next, next, and finish..., saya kira semua berjalan normal. Tapi ternyata tidak, ketika saya buka semua package yang sudah saya install hilang, kembali ke setelan pabrik. 😭😭😭

Saya pun mencoba mencari jawabannya di Internet. dan ternyata banyak kejadian serupa terutama di OS segala umat \`Windows\`. **Sehabis install, semua package hillang dan balik ke setelan pabrik.**

Setelah Googling kesana-kemari, ini adalah salah satu cara yang bisa dilakukan <https://www.r-bloggers.com/2015/06/how-to-upgrade-r-without-losing-your-packages/>. Rasanya bodoh sekali, saya kenapa tidak mencari tahu dahulu sebelum update. Semoga kedepannya lebih berhati-hati, dan tidak terjadi lagi kejadian serupa ya.
