---
title: "Random Thoughts #1"
author: "Muhammad Apriandito"
date: "8/04/2023"
categories:
  - Personal Opinion
  - Random
---

------------------------------------------------------------------------

Ini pukul 23.17 tengah malam, seharusnya saya istirahat tidur atau setidaknya mengerjakan pekerjaan yang menumpuk. Namun entah mengapa malam ini saya sama sekali tidak berminat.

Pikiran saya sedang tidak ingin digunakan untuk hal-hal serius. Sebenarnya buruk juga sih, mengingat tumpukan pekerjaan di meja kerja. Tetapi mau bagaimana lagi? Terkadang saya butuh waktu untuk menekuni hobi, sekedar penyegaran otak dan jiwa. Ya, sejak Apoy lahir, rasanya sangat jarang punya waktu untuk diri sendiri apalagi hobi. Bagaimana tidak, Apoy benar-benar menempel bak perangko, saya lepas sebentar saja sudah menangis. Walaupun begitu, saya juga manusia biasa yang kadang perlu meluapkan hasrat dan ekspresi pribadi. Sejak hadirnya Apoy, hobi-hobi saya terpaksa dikesampingkan, atau lebih tepatnya terlupakan karena tidak sempat.

Ah, terkadang memang terasa menyebalkan. Namun saya tidak boleh egois dan marah, status saya sekarang adalah seorang ayah.

Sebenarnya agak ironis juga. Ketika orang lain menghabiskan waktu luang untuk bersenang-senang dengan hobi atau jalan-jalan, me time saya justru diisi dengan mengasah diri, mencoba hal-hal baru atau sekadar membaca dan mengkaji berbagai pengetahuan. Memang terlihat seperti rutinitas kerja, tetapi bagi saya itu menyenangkan dan otak saya membutuhkannya.

Akhir-akhir ini banyak hal yang saya baca dan teliti, namun belum sempat dipraktikkan. Rencananya ingin saya catat, sebagai memori eksternal agar tidak lupa atau hilang di kemudian hari. Siapa tahu suatu saat bermanfaat jika saya memerlukannya lagi. Semoga kegemaran menulis bisa menjadi hobi baru yang menyenangkan bagi saya, sebagai sarana meluapkan ide-ide di kepala. Ya, mungkin ini satu-satunya pilihan hobi saya saat ini mengingat keterbatasan waktu. Maafkan saya pekerjaan, semestinya malam ini saya menyelesaikanmu. Namun apa daya, saat ini saya benar-benar butuh menuangkan buah pikiran saya dalam tulisan, meski hanya sebentar.
